# Addition & Subtraction

#### Addition

Addition, it is an extremely easy opertation, there is only one condition, the two matrices must have the same dimensions.

The m1 matrix is:

$$
\left[
 \begin{matrix}
   5 & 12 & 6\\
   -3 & 0 & 14\\
  \end{matrix} 
\right]
$$

The m2 matrix is:

$$
\left[
 \begin{matrix}
   9 & 8 & 7\\
   1 & 3 & -5\\
  \end{matrix} 
\right]
$$

It can see they are both 2 by 3 matrices, if want to add that two, all I need to do is add the corresponding entries one with the other.

So the result is the new 2 by 3 matirx:

$$
\left[
 \begin{matrix}
   5+9 & 12+8 & 6+7\\
   -3+1 & 0+3 & 14-5\\
  \end{matrix} 
\right]
$$

___

#### Subtraction

Subtraction is just a type of addition, so the same rule apply there.

The m1 matrix is:

$$
\left[
 \begin{matrix}
   5 & 3\\
   -2 & 4\\
  \end{matrix} 
\right]
$$

The m2 matrix is:

$$
\left[
 \begin{matrix}
   7 & -5\\
   3 & 8\\
  \end{matrix} 
\right]
$$

So the result is the new 2 by 2 matirx:

$$
\left[
 \begin{matrix}
   5-7 & 3+5\\
   -2-3 & 4-8\\
  \end{matrix} 
\right]
$$

____

#### Addition or Subtraction of vectors

Since vectors are nothing more than one dimensional matrices, same rule apply, with vectors, we only care about the length, the two vectors have the same length, so it can calculate.

In [1]:
import numpy as np

#### Addition

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

#### Subtraction

In [5]:
m1 = np.array([[5,3],[-2,4]])
m1

array([[ 5,  3],
       [-2,  4]])

In [6]:
m2 = np.array([[7,-5],[3,8]])
m2

array([[ 7, -5],
       [ 3,  8]])

In [7]:
m1 - m2

array([[-2,  8],
       [-5, -4]])