# Arrays in Python

In [1]:
import numpy as np

### Declaring scalars, vectors and matrices

#### Scalars

In [2]:
# the integer or a float are doing the job

s = 5

In [3]:
s

5

#### Vectors

In [4]:
# by default v is a row vector

v = np.array([5, -2, 4])

In [5]:
v

array([ 5, -2,  4])

#### Matrices

In [6]:
m = np.array([[5, 12, 6],[-3, 0, 14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

#### Data types

In [8]:
type(s)

int

In [9]:
# ndarray means n-dimensional array
# v is a one dimensional array

type(v)

numpy.ndarray

In [10]:
# m is a two dimensional array

type(m)

numpy.ndarray

In [11]:
# this is another way can create a scalar

s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

#### Data shape

In [13]:
# it can know the data dimensional

m.shape

(2, 3)

In [14]:
# in the memory of the computer, this object has 3 (ordered) elements

v.shape

(3,)

In [15]:
# the scalar is a 0 dimensional object thus it has no shape

s_array.shape

()

#### Create a column vector

In [16]:
# it is give the row vector

v.reshape(1,3)

array([[ 5, -2,  4]])

In [17]:
# it is give the column vector

v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])