# Dot Product of Matrices

Multiply a matrix with another matirx using the same concept the dot product, it can multiply two matrices, there is a compatibility measure too, it can only multiply a matrix of dimensions m by n with an n by k matrix, basically the second dimension of the first matirx has to match the first dimension of the second matrix, so it can multiply a 2 by 3 matirx with a 3 by 1 matrix, actually it can multiply it by a 3 by 2, 3 by 3, 3 by 4 and so on until the 3 by k matric, what's important is that those 3 are matching.

Similarly if I want to multiply a 5 by 7 matrix compatible matrices for multiplication are 7 by 1, 7 by 2, 7 by 7 and so on.

When multiplying an m by n matrix with n by k matrix, the output is m by k matrix, for instance a 2 by 3 matrix . 3 by 6 matrix, it will give a 2 by 6 matrix and the 3 by 4 matrix . 4 by 2 matirx, it will give a 3 by 2 matrix or the 100 by 300 matrix . 300 by 3 matrix, it will give a 100 by 3 matrix, so basically whichevey dimension is repeating will disappear in the resulting.
___

#### How do actually multiply matrices ?

There are two matrix, A and B, actually these are two vectors or 3 by 1 matrices, in order to multiply them they need to have matching forms, to find their dot product, it can transpose the first one A and get a 1 by 3 matrix, this is done because when we have a dot product, we always multiply a row vector * column vector, the result of this multiplication is a 1 by 1 form or a scalar, it means reached this scalar by multiplying the corresponding elements and summing everything up.

A is:

$$
\left[
 \begin{matrix}
   2\\
   8\\
   -4\\
  \end{matrix} 
\right]
$$

B is:

$$
\left[
 \begin{matrix}
   1\\
   -7\\
   3\\
  \end{matrix} 
\right]
$$

Transpose A:

$$
\left[
 \begin{matrix}
   2 & 8 & -4\\
  \end{matrix} 
\right]
$$

Transpose A . B:

$$
\left[
 \begin{matrix}
   -66\\
  \end{matrix} 
\right]
$$
___

Take two matrices and multiply them, there are two matrices A and B, the A matrices is 2 by 3, the B matrices is 3 by 2.

The first thing need to do is check their compatibility, 2 by 3 * 3 by 2, so the forming is matching, the next step is find the shape of the output matrix, the maching dimesion disappears, so the result is 2 by 2, finally it must do that multiplication itself, there are two important things, matrices are nothing more than a collection of vectors, when it have a dot product, it always multiply a row vector times a column vector.

When A . B, it need to find the dot product of the vectors that made of, it means divid the two matrices into two vectors, so the result is below, notice that the row vectors from the first matirx determine the row and the output matrix in the same way, the column vectors from the second matrix determine the column of the respective value.


A is:

$$
\left[
 \begin{matrix}
   5 & 12 & 6\\
   -3 & 0 & 14\\
  \end{matrix} 
\right]
$$

B is:

$$
\left[
 \begin{matrix}
   2 & -1\\
   8 & 0\\
   3 & 0\\
  \end{matrix} 
\right]
$$

A . B:

$$
\left[
 \begin{matrix}
   5 * 2 + 12 * 8 + 6 * 3 & 5 * -1 + 12 * 0 + 6 * 0 \\
   -3 * 2 + 0 * 8 + 14 * 3 & -3 * -1 + 12 * 0 + 14 * 0\\
  \end{matrix} 
\right]
$$

___

If there are two matrices, A is 3 by 4, B is 2 by 3, then it want to have a dot product result, in face it's nothing to, because the two matrices are not compatible, so there is no way to do the dot product.

In [1]:
import numpy as np

#### Scalar * matrix

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
# the shape of matrix doesn't change, it just get scaled
# it keep the shape and multiply each element by three

3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

#### Matrix * matrix

In [4]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [5]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [6]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [7]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [8]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])