# Errors when Adding Matrices

Scalars are more peculiar than high dimension object, because they are single numbers.

In [1]:
import numpy as np

#### Addition

In [2]:
5 + 5

10

In [3]:
10 - 4 

6

#### Addition of matrices

In order to add vectors and matrices, their forms must match, so it is not allowed to add vectors of different length and matrices with different dimensions.

In [4]:
m1 = np.array([[5,12,6],[-3,0,14]])

In [5]:
m2 = np.array([[5,3],[-2.4]])

In [6]:
# mathematically there operations don't make sense, so they can not be executed

m1 + m2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

#### Addition of vectors

In [7]:
v1 = np.array([1,2,3,4,5])

In [8]:
v2 = np.array([1,2,3,4])

In [9]:
# mathematically there operations don't make sense, so they can not be executed

v1 + v2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

### Exceptions (addition with a scalar)

In [10]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
# it can add scalars to matirces and vectors
# it can see that 1 was added element wise
# mathematically this operation is not allowed as the shapes are different but in programming or at least in Python is works

m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [12]:
v1

array([1, 2, 3, 4, 5])

In [13]:
# mathematically this operation is not allowed as the shapes are different but in programming or at least in Python is works
# it was very important to be aware of this peculiarity

v1 + 1

array([2, 3, 4, 5, 6])

In [14]:
# the result has a meaning in terms of arrays but not in terms of linear algebra
# that is also one of the big differences between the concepts of ndarray and tensors

m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [15]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])