# Tensors

The mathematical concept of a tensor could be broadly explained in this way, a scalar has the lowest dimensionality and is always one by one, it can thought of as a vector of length one or one by one matrix, it is followed by a vector where each element of that vector is scalar, the dimensions of a vector are nothing but m x 1 or 1 x m matrices, then we have matrices which are nothing more than a collection of vectors, the dimensions of a matrix are m by n.

In other words a matrix is a collection of n vectors of dimensions m by 1 or m vectors of dimensions n by 1, furthermore since scalars make up vectors, it can think of a matrix as a collection of scalars.

Tensor is the most general concept, scalar, vectors and matrices are all tensors of rank 0, rank 1 and rank 2.

Tensor are simply a generalization of the concepts we have seen so far, object we haven't seen is a tensor of rank 3 dimensions, it dimensions k by m by n, it can be thought of as a collection of matrices, in terms of programming tensor is no different than in ndarray and in fact tensors can be stored in ndarrays and that's how we often deal with the issue.

In [1]:
import numpy as np

In [2]:
m1 = np.array([[5, 12, 6],[-3, 0 ,16]])
m1

array([[ 5, 12,  6],
       [-3,  0, 16]])

In [3]:
m2 = np.array([[9, 8, 7],[1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 16]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [5]:
# it is 2 by 2 by 3 object, it contains two matrices 2 by 3

t.shape

(2, 2, 3)

In [6]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

In [7]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])