# Transpose of a Matrix

Let X be the column vector, look likes below, there is special operation which can turn it into a row vector, it can transpose it, transposing the column vector would yield in a row vector, the transpose denote with the letter T as a superscript, therefore X transposed or the column vector 1,2,3 transposed equals the row vector 1,2,3, this is a pretty neat operation, if transpose X twice it will get X.

This is column vector X:

$$
\left[
 \begin{matrix}
   1\\
   2\\
   3\\
  \end{matrix} 
\right]
$$

The transpose vector is:

$$
\left[
 \begin{matrix}
   1 & 2 & 3\\
  \end{matrix} 
\right]
$$
___

There are several very important considerations, when transpose a vector, it isn't losing any information, the values are not changing or transforming only their position is; second tranposing the same vector twice yields the initial vector; third in the example, the X is 3 by 1 matrix and length is 3, when transposing it remained a vector of length 3 but it became 1 by 3 matrix, the third consideration gives a peek into how transposing works for matrices.

It turns all of its rows into columns and vice versa, in terms of dimensions when transposed m by n matrix, it will become n by m matrix.

For example, the is the matrix A and transposed it, it will become below, it can know the original matrix is 2 by 3, when transposing, the matrix becomes 3 by 2, transposed the matrix A means transposing each of those vectors and put them back together, so transposing matrices is nothing more than transposing a bunch of vectors.

The A matrix:

$$
\left[
 \begin{matrix}
   5 & 12 & 6\\
   -3 & 0 & 14\\
  \end{matrix} 
\right]
$$


The transposed matrix:

$$
\left[
 \begin{matrix}
   5 & -3\\
   12 & 0\\
   6 & 14\\
  \end{matrix} 
\right]
$$

In [1]:
import numpy as np

#### Transposing scalars

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [5]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [6]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [7]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

#### Transposing scalars

In [8]:
s = np.array([5])

In [9]:
s.T

array([5])

#### Transposing vectors

In [10]:
x = np.array([1,2,3])

In [11]:
# in python, the 1D array don't really get transposed(in the memory of the computer)

x.T

array([1, 2, 3])

In [12]:
x_reshape = x.reshape(1,3)
x_reshape

array([[1, 2, 3]])

In [13]:
# if it reshape it into a three by one matrix or a two dimensional array, it will be albe to transpose it

x_reshape.T

array([[1],
       [2],
       [3]])